# Generated by Django 5.0.6 on 2024-06-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='seats',
            field=models.IntegerField(default=0),
        ),
    ]
