# Generated by Django 5.0.6 on 2024-07-04 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('country_location', models.IntegerField()),
                ('logo', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.IntegerField()),
                ('location_from', models.IntegerField()),
                ('location_to', models.IntegerField()),
                ('leave_time', models.IntegerField()),
                ('arrival_time', models.IntegerField()),
                ('bus', models.IntegerField()),
                ('trip_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
