# Generated by Django 5.0.4 on 2024-07-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_agency_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
