# Generated by Django 5.0.4 on 2024-07-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_trip_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='agency',
        ),
        migrations.AddField(
            model_name='agency',
            name='name',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
