# Generated by Django 5.0.4 on 2024-07-06 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_book_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=255)),
                ('number', models.IntegerField()),
                ('trip', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('idcn', models.CharField(default=0, max_length=255)),
                ('code', models.CharField(default=0, max_length=10)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
