# Generated by Django 5.0.4 on 2024-07-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
