# Generated by Django 5.0.4 on 2024-07-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
