# Generated by Django 5.0.4 on 2025-09-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_agency_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trip',
            name='arrival_time',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='leave_time',
            field=models.TimeField(),
        ),
    ]
