# Generated by Django 5.0.4 on 2024-08-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20240808_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='leave_time',
            field=models.TimeField(),
        ),
    ]
