# Generated by Django 5.0.4 on 2024-08-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20240808_0918'),
        ('booking', '0015_auto_20240808_0950'),
    ]

    operations = [
    ]
