# Generated by Django 5.0.4 on 2024-08-08 09:06

from django.db import migrations
from django.db import migrations


def clear_arrival_time(apps, schema_editor):
    trip = apps.get_model('booking', 'trip')
    trip.objects.update(arrival_time=None)


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_merge_0014_auto_20240808_0918_0015_auto_20240808_0950'),
    ]

    operations = [
        migrations.RunPython(clear_arrival_time),
    ]
