# Generated by Django 5.0.4 on 2024-08-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20240808_1006'),
    ]

    operations = [
        # Drop the old column
        migrations.RemoveField(
            model_name='trip',
            name='arrival_time',
        ),
        # Add the new column
        migrations.AddField(
            model_name='trip',
            name='arrival_time',
            field=models.TimeField(null=True),  # Adjust nullability and defaults as needed
        ),
    ]
